require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'

# Rails-specific configuration
Rails:
  Enabled: true

# RSpec-specific configuration
RSpec:
  Enabled: true

# Performance-specific checks
Performance:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/application_events_controller.rb'
    - 'app/controllers/applications_controller.rb'
    - 'app/controllers/job_events_controller.rb'
    - 'app/controllers/jobs_controller.rb'

Rails/ReflectionClassName:
  Exclude:
    - 'app/models/**/*'

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/**/*'

# Example of overriding a specific cop
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'class_methods', 'instance_methods']
